# Generated by Django 3.1.5 on 2021-01-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('cargo_postula', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('carnet_extranjeria', models.TextField()),
                ('l_n_pais', models.CharField(max_length=80)),
                ('l_n_departamento', models.CharField(max_length=80)),
                ('l_n_provincia', models.CharField(max_length=80)),
                ('l_n_distrito', models.CharField(max_length=80)),
                ('l_d_departamento', models.CharField(max_length=80)),
                ('l_d_provincia', models.CharField(max_length=80)),
                ('l_d_distrito', models.CharField(max_length=80)),
                ('l_d_direccion', models.CharField(max_length=100)),
                ('org_politica_postulate', models.CharField(max_length=90)),
                ('link_foto', models.URLField()),
            ],
        ),
    ]
