# Generated by Django 3.1.5 on 2021-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionPolitica',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('organizacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SentenciaPenalDelito',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('delito', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cargoeleccion',
            name='total_anhio_eleccion',
            field=models.IntegerField(null=True),
        ),
    ]
