# Generated by Django 3.1.5 on 2021-01-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidato',
            table='candidato',
        ),
    ]
