# Generated by Django 3.0 on 2021-02-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionPolitica',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.CharField(default='-', editable=False, max_length=200)),
            ],
            options={
                'db_table': 'organizacion_politica',
            },
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url',
            field=models.CharField(default='-', editable=False, max_length=200),
        ),
    ]
