# Generated by Django 3.0 on 2021-02-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_auto_20210211_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizacionPolitica',
            new_name='OrganizacionesPoliticas',
        ),
        migrations.RenameField(
            model_name='organizacionespoliticas',
            old_name='nombre',
            new_name='organizacion_politica',
        ),
        migrations.AlterModelTable(
            name='organizacionespoliticas',
            table='organizaciones_politicas',
        ),
    ]
