# Generated by Django 3.1.5 on 2021-01-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_auto_20210118_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='dni_candidato',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato'),
        ),
        migrations.AlterUniqueTogether(
            name='experiencialaboral',
            unique_together={('ruc_empresa_laboral', 'desde', 'hasta', 'dni_candidato')},
        ),
        migrations.CreateModel(
            name='TieneTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'tiene_trayectoria_partidaria',
            },
        ),
        migrations.CreateModel(
            name='TieneInfoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'tiene_informacion_adicional',
            },
        ),
        migrations.CreateModel(
            name='TieneBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'tiene_bien_renta',
            },
        ),
        migrations.CreateModel(
            name='SentenciaPenal',
            fields=[
                ('n_experiente_penal', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fecha_sentencia_firme', models.CharField(max_length=40)),
                ('organo_judicial', models.CharField(max_length=100)),
                ('delito_penal', models.CharField(max_length=120)),
                ('fallo_pena', models.CharField(max_length=120)),
                ('modalidad_penal', models.CharField(max_length=100)),
                ('cumplimiendo_del_fallo', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'sentencia_penal',
            },
        ),
        migrations.CreateModel(
            name='SentenciaCivil',
            fields=[
                ('materia_demanda_civil', models.CharField(max_length=140)),
                ('n_experiente_civil', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('organo_judicial', models.CharField(max_length=100)),
                ('fallo_pena', models.CharField(max_length=120)),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'sentencia_civil',
            },
        ),
        migrations.CreateModel(
            name='Renuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organización_politica', models.CharField(max_length=140)),
                ('anhio', models.CharField(max_length=10)),
                ('comentario', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'renuncia',
            },
        ),
        migrations.CreateModel(
            name='InformacionAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'informacion_adicional',
            },
        ),
        migrations.CreateModel(
            name='EstudioUniversitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_estudio_universitario', models.CharField(max_length=10)),
                ('centro_estudio_universitario', models.CharField(max_length=200)),
                ('concluyo_estudio_universitario', models.CharField(max_length=10)),
                ('grado_universitario', models.CharField(max_length=150)),
                ('es_egresado_universitario', models.CharField(max_length=10)),
                ('anhio_obtencion_universitario', models.CharField(max_length=10)),
                ('comentario_estudio_universitario', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'estudio_universitario',
            },
        ),
        migrations.CreateModel(
            name='EstudioTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_estudio_tecnico', models.CharField(max_length=10)),
                ('centro_estudio_tecnico', models.CharField(max_length=200)),
                ('carrera_tecnica', models.CharField(max_length=200)),
                ('concluyo_estudio_tecnico', models.CharField(max_length=10)),
                ('comentario_estudio_tecnico', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'estudio_tecnico',
            },
        ),
        migrations.CreateModel(
            name='EstudioPostgrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_postgrado', models.CharField(max_length=10)),
                ('centro_estudio_postgrado', models.CharField(max_length=200)),
                ('grado_postgrado', models.CharField(max_length=200)),
                ('concluyo_estudio_postgrado', models.CharField(max_length=10)),
                ('es_egresado_postgrado', models.CharField(max_length=10)),
                ('es_maestro', models.CharField(max_length=10)),
                ('es_doctor', models.CharField(max_length=10)),
                ('anhio_obtencion_postgrado', models.CharField(max_length=10)),
                ('comentario_estudio_postgrado', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'estudio_postgrado',
            },
        ),
        migrations.CreateModel(
            name='EstudioNoUniversitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_estudio_no_universitario', models.CharField(max_length=10)),
                ('centro_estudio_no_universitario', models.CharField(max_length=200)),
                ('carrera_no_universitaria', models.CharField(max_length=200)),
                ('concluyo_estudio_no_universitario', models.CharField(max_length=10)),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'estudio_no_universitario',
            },
        ),
        migrations.CreateModel(
            name='EducacionBasica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_estudio_primaria', models.CharField(max_length=10)),
                ('concluyo_primaria', models.CharField(max_length=10)),
                ('tiene_estudio_secundaria', models.CharField(max_length=10)),
                ('concluyo_secundaria', models.CharField(max_length=10)),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'educacion_basica',
            },
        ),
        migrations.CreateModel(
            name='CargoPartidario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_politica', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=300)),
                ('desde', models.CharField(max_length=20)),
                ('hasta', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'cargo_partidario',
            },
        ),
        migrations.CreateModel(
            name='CargoEleccionPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_politica', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=300)),
                ('desde', models.CharField(max_length=20)),
                ('hasta', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
                ('dni_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'cargo_eleccion_popular',
            },
        ),
        migrations.CreateModel(
            name='BienRenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anhio', models.CharField(max_length=10)),
                ('total_bien_muebles', models.FloatField()),
                ('total_ingresos', models.FloatField()),
            ],
            options={
                'db_table': 'bien_renta',
                'unique_together': {('total_bien_muebles', 'total_ingresos')},
            },
        ),
        migrations.CreateModel(
            name='BienInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo_bien', models.CharField(max_length=100)),
                ('direccion_inmueble', models.CharField(max_length=300)),
                ('esta_inscrito_sunarp', models.CharField(max_length=10)),
                ('partida_inmueble', models.CharField(max_length=100)),
                ('valor_inmueble', models.FloatField()),
                ('comentario_inmueble', models.TextField()),
                ('total_ingresos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidato')),
            ],
            options={
                'db_table': 'bien_inmueble',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('vehiculo', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=10)),
                ('caracteristicas_vehiculo', models.TextField()),
                ('valor', models.FloatField()),
                ('comentario_vehiculo', models.TextField()),
                ('total_bien_muebles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_bien_muebles', to='elecciones.candidato')),
                ('total_ingresos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_ingresos', to='elecciones.candidato')),
            ],
            options={
                'db_table': 'vehiculo',
                'unique_together': {('total_bien_muebles', 'total_ingresos', 'placa_vehiculo')},
            },
        ),
        migrations.AddConstraint(
            model_name='tienetp',
            constraint=models.UniqueConstraint(fields=('dni_candidato',), name='unique dni_tp'),
        ),
        migrations.AddConstraint(
            model_name='tieneinfoa',
            constraint=models.UniqueConstraint(fields=('dni_candidato',), name='unique dni_infoA'),
        ),
        migrations.AddConstraint(
            model_name='tienebr',
            constraint=models.UniqueConstraint(fields=('dni_candidato',), name='unique dni_tieneBR'),
        ),
        migrations.AlterUniqueTogether(
            name='renuncia',
            unique_together={('dni_candidato', 'organización_politica', 'anhio')},
        ),
        migrations.AddConstraint(
            model_name='cargopartidario',
            constraint=models.UniqueConstraint(fields=('dni_candidato',), name='unique dni_carg_parti'),
        ),
        migrations.AddConstraint(
            model_name='cargoeleccionpopular',
            constraint=models.UniqueConstraint(fields=('dni_candidato',), name='unique dni_elecc_popu'),
        ),
    ]
