# Generated by Django 3.0 on 2021-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_auto_20210212_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaEdad',
            fields=[
                ('edad', models.IntegerField()),
                ('organizacion_politica', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tabla_edad',
            },
        ),
    ]
