# Generated by Django 3.0 on 2021-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_tablaedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaedad',
            name='organizacion_politica',
            field=models.CharField(default='-', editable=False, max_length=250),
        ),
    ]
