# Generated by Django 3.1.7 on 2021-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0006_delete_tablaedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaEdad',
            fields=[
                ('edad', models.IntegerField()),
                ('organizacion_politica', models.CharField(default='-', editable=False, max_length=250)),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tabla_edad',
            },
        ),
    ]
