# Generated by Django 3.1.7 on 2021-03-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_auto_20210309_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablaedad',
            old_name='dni',
            new_name='dni_candidato',
        ),
    ]
