# Generated by Django 3.0 on 2021-02-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_auto_20210212_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablaEdad',
        ),
    ]
